### ISSUE TITLE
code for provideed

### ISSUE THREAD

**Issue by anbadon** [ChenQian0618/TFN#1]
Hello, can your code be provided?

**Comment by qianshiguang1** [comment]
您好，请问可以更新这个代码吗？谢谢

**Comment by dream857** [comment]
> 您好，请问可以更新这个代码吗？谢谢

你收到回复了吗？

**Comment by qianshiguang1** [comment]
还没有

**Comment by qianshiguang1** [comment]
> > 您好，请问可以更新这个代码吗？谢谢
> 
> 你收到回复了吗？

还没有

**Comment by DVA12** [comment]
什么时候提供代码呢？

**Comment by ChenQian0618** [comment]
这写着，论文发表后才公开代码，没公开代码说明论文还没中啊。

我也很尴尬啊...

**Comment by dream857** [comment]
但是我们已经在网上看到了你这篇论文，跟着论文链接进来的。...................

**Comment by DVA12** [comment]
对啊，看到论文才来的

**Comment by liguge** [comment]
> 这写着，论文发表后才公开代码，没公开代码说明论文还没中啊。
> 
> 我也很尴尬啊...

论文还没中啊，这么好的文章。现在中个论文这么难？投稿到mssp嘛？

**Comment by ChenQian0618** [comment]
> > 这写着，论文发表后才公开代码，没公开代码说明论文还没中啊。
> > 我也很尴尬啊...
> 
> 论文还没中啊，这么好的文章。现在中个论文这么难？投稿到mssp嘛？

是的，MSSP退稿重投，不过意见还行，顺利的话就2月，不顺利的话就说不准了。

目前的论文和arxiv版本有较大改动，具体而言，补充了和SincNet、WKN等先进方法的对比，更广泛的可解释性实验以及few-show等场景的表现，见刊后可以具体看看

**Comment by ChenQian0618** [comment]
> 但是我们已经在网上看到了你这篇论文，跟着论文链接进来的。...................

arxiv版本和见刊还是有很大区别的....

**Comment by liguge** [comment]
> > > 这写着，论文发表后才公开代码，没公开代码说明论文还没中啊。
> > > 我也很尴尬啊...
> > 
> > 
> > 论文还没中啊，这么好的文章。现在中个论文这么难？投稿到mssp嘛？
> 
> 是的，MSSP退稿重投，不过意见还行，顺利的话就2月，不顺利的话就说不准了。
> 
> 目前的论文和arxiv版本有较大改动，具体而言，补充了和SincNet、WKN等先进方法的对比，更广泛的可解释性实验以及few-show等场景的表现，见刊后可以具体看看
方便加个wx一起交流吗？我最近也在做这个方向。北交大的PHD，我的wx是   17853131673

**Comment by liguge** [comment]
> > > 这写着，论文发表后才公开代码，没公开代码说明论文还没中啊。
> > > 我也很尴尬啊...
> > 
> > 
> > 论文还没中啊，这么好的文章。现在中个论文这么难？投稿到mssp嘛？
> 
> 是的，MSSP退稿重投，不过意见还行，顺利的话就2月，不顺利的话就说不准了。
> 
> 目前的论文和arxiv版本有较大改动，具体而言，补充了和SincNet、WKN等先进方法的对比，更广泛的可解释性实验以及few-show等场景的表现，见刊后可以具体看看

方便加个wx一起交流吗？我最近也在做这个方向。北交大的PHD，我的wx是 17853131673

**Comment by liguge** [comment]
半年过去了，我还在期期待这篇文章的发表。

**Comment by ChenQian0618** [comment]
The code has been uploaded
