### ISSUE TITLE
半年过去了，我还在期待这篇文章的发表

### ISSUE THREAD

**Issue by liguge** [ChenQian0618/TFN#2]

**Comment by ChenQian0618** [comment]
...，
2023-01-10，submitted to MSSP;
2023-04-25，decision-rejct & resubmit;
2023-06-14, resubmission;
2023-08-17, decision-major revision;
2023-09-01, R1 returned;

**Comment by liguge** [comment]
> ...， 2023-01-10，submitted to MSSP; 2023-04-25，decision-rejct & resubmit; 2023-06-14, resubmission; 2023-08-17, decision-major revision; 2023-09-01, R1 returned;

这也是相当曲折了。。我是用了一年，，

**Comment by ChenQian0618** [comment]
> ...， 2023-01-10，submitted to MSSP; 2023-04-25，decision-reject & resubmit; 2023-06-14, resubmission; 2023-08-17, decision-major revision; 2023-09-01, R1 returned;

2023-11-03,  R2 decision-minor revision
2023-11-08,  R2 returned
2023-11-15, accepted

**I am currently organizing the code and will release it soon.**

**Comment by liguge** [comment]
> > ...， 2023-01-10，submitted to MSSP; 2023-04-25，decision-reject & resubmit; 2023-06-14, resubmission; 2023-08-17, decision-major revision; 2023-09-01, R1 returned;
> 
> 2023-11-03, R2 decision-minor revision 2023-11-08, R2 returned 2023-11-15, accepted
> 
> **I am currently organizing the code and will release it soon.**

恭喜恭喜。
