### ISSUE TITLE
开源代码里面的cnn主干没有看到resnet

### ISSUE THREAD

**Issue by tangsipeng** [ChenQian0618/TFN#4]
感谢你的工作，我在参考论文和代码过程中没有看到resnet，请问能否更新resnet相关的代码，方便复现实现结果。
<img width="623" alt="image" src="https://github.com/ChenQian0618/TFN/assets/4188431/02db74cd-2326-4097-a4de-f7804b67db6f">

**Comment by ChenQian0618** [comment]
resnet和其他网络可直接参照https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark/tree/master/models
